### ISSUE TITLE
Organization of the downloaded zip archive

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#219]
When reusing specifications, in the downloaded zip file, they are on the same level with the "main" specification, which is a bit confusing. It might be worth thinking about reorganization of the zip file, e.g. the reused specs could be in an additional `reused` subfolder or something like that.

This of course impacts the path to imported schemas, e.g. in XSD, etc.

**Comment by sstenchlak** [comment]
I agree with Martin. The idea is that each data specification is an independent folder containing the individual artifacts. The ZIP file is structured so that in the root, there are the individual specifications that are meant to be placed in their respective locations. **They are not meant to be on the same level.** Each specification can specify its public base URL, which will affect links between files from different specifications.

It is possible to have one specification with its base URL as a subdirectory of another specification, but then you would need to move the files by yourself.

If you meant it for the testing phase when specifications are not yet published, it is a reasonable request.

For specifications inside other specifications, this would make sense and it would be handled in core@v2.

Please reopen if you do not agree.
