### ISSUE TITLE
Common keys type and id for PSM classes in JSON schema

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#245]
For each PSM class with a PIM interpretation, the following JSON schema structure should be generated:

```json
{
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "format": "iri"
    },
    "id": {
      "type": "string",
      "format": "iri"
    },
    "other_property": {}
  }
}
```

**Comment by jakubklimek** [comment]
This is, however, specific to RPP. For FOSes we need 
1) iri instead of id
2) typ instead of type
3) type is either a const (based on the PSM) or an array (to allow extensions to be created)
e.g.:
```json
{
	"type": "object",
	"properties": {
		"iri": {
			"type": "string",
			"format": "iri"
		},
		"typ": {
			"oneOf": [{
					"const": "Pracovní místo"
				},
				{
					"type": "array",
					"contains": {
						"const": "Pracovní místo"
					},
					"items": {
						"type": "string"
					}
				}
			]
		}
	}
}
```

**Comment by martinnec** [comment]
Every concrete set up is specific for something. So it needs to be configurable. There should always be:

1. item for resource IRI (label configurable, e.g., "id" / "iri")
2. item for resource type(s) (label configurable, e.g., "type" / "typ")

For 1 it will always be 

```json
{
  "type": "string",
  "format": "iri"
}
```

For 2 it will always be

```json
{
  "oneOf": [{
    "const": "$T-LABEL(C)$"
  },
  {
    "type": "array",
    "contains": {
      "const": "$T-LABEL(C)$"
  },
  "items": {
    "type": "string"
  }
}
```

where `T-LABEL(C)` is a technical label of a PSM class `C` with a PIM interpretation. I am not sure with `T-LABEL(C)` but we can discuss this further.

**Comment by jakubklimek** [comment]
I agree. However, I think that `T-LABEL(C)` will have to be different from the technical label. It can contain arbitrary text (which is then mapped in a JSON-LD context to an IRI, like `Pracovní místo`). The same text is, however, not e.g. a valid XML element name where technical labels are used already.

**Comment by martinnec** [comment]
Could we have `skos:prefLabel(CIM(C))` instead of `T-LABEL(C)`?

**Comment by sstenchlak** [comment]
So far, I've implemented the "basic" type key according to the first comment.

**Comment by sstenchlak** [comment]
Hi @jakubklimek, I'm just curious. What is the reason behind `skos:prefLabel` as a type? Why not `rdf:type`? And why do we need the type at all (besides the cases when multiple different types of entities may be present)?

**Comment by jakubklimek** [comment]
@sstenchlak I think there is a misunderstanding. In RDF data instances, i.e. when loaded from JSON-LD with context, `rdf:type` is still to be used as a type.

However, here, we are talking about what text should be used in JSON-LD instances to indicate the type. e.g.
```json
{
   "typ": "Pracovní místo"
}
```
The question is where do we get the text `Pracovní místo`. So far, we used technical labels `T-LABEL(C)`. However, that would result in something like
```json
{
   "type": "pracovní-místo"
}
```
which is not desirable.
Nevertheless, in CIM, we have the text `Pracovní místo`. But it is in `skos:prefLabel(CIM(C))` - so that is what we are discussing here.

Regarding the part "why do we need a type at all" - there are two reasons:
1. We use the type for [JSON-LD type-scoped contexts](https://www.w3.org/TR/json-ld11/#dfn-type-scoped-context)
2. We need the type so that when loaded using a JSON-LD processor, we get the triple with `rdf:type` predicate on the output. Without this, there would be nothing in the input JSON to generate this triple from.

**Comment by jakubklimek** [comment]
I believe this is resolved.
