### ISSUE TITLE
Regular expressions are sometimes not generated in JSON Schema

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#302]
See [this specification](https://xn--slovnk-7va.gov.cz/generujeme/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F71514c1a-9987-49eb-8764-fa1122452967&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1673547545020-bc75-0287-9adf) and see "kód agendy". It has a regex defined, but nothing is generated in the JSON Schema.

**Comment by sstenchlak** [comment]
The problem is that the specification was created long ago, and continuous changes in the code made some data inconsistent. I publish migrations, but only for significant changes, and this wasn't one of them. I can analyze the impact and fix all problems if you want.

Otherwise, the fix is: Change a datatype to something else and apply changes. Change the datatype back and apply again.

**Comment by jakubklimek** [comment]
I think it is OK like this, when we know what to do about it.
