### ISSUE TITLE
Wrong classes created on import when creating AP (problem with attributes?)

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#619]
![image](https://github.com/mff-uk/dataspecer/assets/718827/16f98b21-a913-4609-8597-52fbd3ef8f24)
(see the domain and range of theme clases which do not belong there)

Happened when trying to create an AP of https://mff-uk.github.io/demo-specifications/test1/

**Comment by sstenchlak** [comment]
Its because you made (in the original vocabulary) two entities with the same IRI. See dcat:theme. This broke the owl export that it generated triples from both properties under the same iri. Import then correctly created these two metaclasses as a union of all domains and ranges for the affected property.

**Comment by jakubklimek** [comment]
Yes, thats it, Thanks.
