### ISSUE TITLE
Duplicate objects in JSON part of generated specification

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#672]
Maybe related to #671 , but see the duplicate chapters in the JSON part of [this specification](https://pod-test.dia.gov.cz/otevřené-formální-normy/registr-práv-a-povinností/dokumenty-převodu-agend/2024-09-01/#specifikace-struktury-pro-dokument-prevodu-agend) based on [this project](https://xn--slovnk-7va.gov.cz/generujeme/specification?dataSpecificationIri=https:%2F%2Fofn.gov.cz%2Fdata-specification%2Fde3ba995-4a18-4b0a-96c0-dbac77ee3985).

![image](https://github.com/user-attachments/assets/30e1425f-cfd4-4f7e-85c1-e820bbeb6cf7)

**Comment by sstenchlak** [comment]
This is de facto correct. In a structural model, if you create multiple properties with the same end object (in this case, we have Schvaluje předání působnosti, Přebírá působnost, Převádí působnost — all three having Orgán veřejné moci as a data type), then the end object is created for each of its properties. This allows for different sub-properties and other parameters for each of these objects. Therefore, it is correct that there are multiple instances of Orgán veřejné moci in the generated documentation.

We do not yet support a configuration that would allow you to prefer reusing those objects instead of creating new ones, nor do we have an option in the UI to reuse them manually without explicitly creating a new data structure and reusing it in the traditional way.

As an example, consider a data structure for a Person with some basic properties and two associations: hasFriends and hasEnemies. These associations would point back to Person, but in the structure model, we might not want to include those two associations, which leads to two different structures — ComplexPerson (interprets Person) and SimplePerson (also interprets Person). This implies that the user must be aware of the concept of reusing objects within a single structure, as there are cases when it is necessary and cases when it is not.

The options are:

- Implement something like a "smart merge," where identical sub-schemas are merged before the generation starts. This should not be too difficult.
  - Implement a simpler version, as in this case, the OVM is empty and therefore considered as a primitive data type. - **I just realized that this is probably the correct solution right now as it fixes the mentioned problem and also it probably does not make much sense to have different "entities" representing a simple data type.**
- Implement an option to reuse already existing sub-structures instead of creating new ones. This mostly affects only the UI; everything else should work as expected.

Regarding namings:

This is already implemented - you can name each object on a structure level differently using the technical labels, hence creating something like a Simple and Complex person in possible.

**Comment by sstenchlak** [comment]
We decided for "položka typu IRI (Orgán veřejné moci)" with link to the semantic layer + not including additional structure information.
