### ISSUE TITLE
XSD import path slightly incorrect

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#715]
In [this specification](https://slovník.gov.cz/generujeme/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F921efca8-2017-4881-914f-b46137fc11e4) when ZIP is generated, the path to the reused XSD in the generated XSD is sligtly incorrect (`.` vs `..`):
```xml
<xs:import schemaLocation="./společné-specifikace/person-in-relationship-with-a-document/schema.xsd"/>
```
should be
```xml
<xs:import schemaLocation="../společné-specifikace/person-in-relationship-with-a-document/schema.xsd"/>
```

This probably has to do with the setting/circumstance whether the main XSD is in the root of the zip (then `.` is fine) or in a separate folder (then `..` is necessary).

**Comment by sstenchlak** [comment]
No, that is correct, check base urls of both specifications.

- https://pod-test.dia.gov.cz/otevřené-formální-normy/dokumenty-z-formulářů-ZoPDS/draft/společné-specifikace
- https://pod-test.dia.gov.cz/otevřené-formální-normy/dokumenty-z-formulářů-ZoPDS/draft/

The only problem I see is that the final references across different specifications are relative, not absolute.

**Comment by jakubklimek** [comment]
It was generated in the same way even without Base URL.

**Comment by sstenchlak** [comment]
I still do not think this is an error. The path started with a dot because the relative path to the other specification started with the `společné-specifikace` directory next to the generated xsd schema. Nevertheless, https://github.com/mff-uk/dataspecer/commit/d0821c76d2b98573a9b19df0f7bf790d7a3e7064 uses absolute paths for cross-specification references making this issue irrelevant.
