### ISSUE TITLE
AP of AP use case: All APs are generated in DSV output

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#788]
In [this spec](https://backend.dataspecer.com/preview/en/index.html?iri=c0d97703-fcdb-4099-b247-eea13eb90115) I do an AP of an AP. In the documentation, only the class profiles of the current AP (of AP) are included. However, in the DSV, also the other AP is included, which is unexpected.

**Comment by skodapetr** [comment]
How do you export the DSV? Can you elaborate using like X, Y = profile of X and Z = profile oh Y? 
Are both Y a Z part of the same model?

**Comment by jakubklimek** [comment]
It is [this spec](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=c0d97703-fcdb-4099-b247-eea13eb90115&view-id=6b1bd0bb-ca9f-4821-b04a-e98edea825b2) - DCAT-AP, profile of DCAT-DAP, profile of DCAT.

**Comment by skodapetr** [comment]
Seems like the problem is that when specification is beeing exported all SemanticModel are used. I've tested his by creating two semantic models, each one with a class. Both classes were exported. From this perspactive the bahavour is same for DSV and vocabularies.

This issues suggest that there is a "main" SemanticModel, probably the first one. And only content of this model should be exported to the specification. I.e. only content of this model shuld be given to DSV for export.
